### ISSUE TITLE
Autocomplete

### ISSUE THREAD

**Issue by chirukinbb** [lojadev5/opencart-phpstorm#2]
Hi, thx for addon 
but have a problem^
$this-> autocomplete work
$this->load(or another, whitch light by autocompleter) autocomplete doesn't work
how to enable all levels for autocomlete? and possible enable in autocomplete classes of controllers and models?

**Comment by lojadev5** [comment]
Foxed on

**Comment by lojadev5** [comment]
Duplicate of #1
